services:
    postgres:
        image: postgres:latest
        container_name: db
        networks:
            - boilerplate_network
        ports:
            - ${POSTGRES_PORT}:5432
        env_file:
            - ./.env.docker
        restart: always
    test_db:
        image: postgres
        container_name: test_db
        networks:
            - boilerplate_network
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${TEST_POSTGRES_PORT}:5432
        env_file:
            - ./.env.docker
    redis:
        image: redis/redis-stack:latest
        container_name: redis
        networks:
            - boilerplate_network
        ports:
            - ${REDIS_PORT}:6379
        env_file:
            - ./.env.docker
        restart: always

networks:
    boilerplate_network:
        driver: bridge